services:
  blue:
    image: dlwjddus1112/fc-backend:latest
    container_name: blue
    restart: always
    ports:
      - 8081:8080

  green:
    image: ksg1227/fc-backend:latest
    container_name: green
    restart: always
    ports:
      - 8082:8080